### PR TITLE
Fix rescan paths

### PR DESCRIPTION
**Pull request by robbevp**
For the rescan#read, we need to allow no ID to be passed. Before this `/api/rescan/undefined` was fetched.

### CODE REVIEW

**Review by chvp — COMMENTED** [review]
Ah, this slipped in to #17 as well. I feel like we should special case the read for rescan, instead of changing this for every route.

**Comment by robbevp** [comment]
Yeah, we should not allow this for every method and/or passing no param when one is required feels weird.

I think a special case is a good idea, but I want to think about a better system for this than checking against a series of strings.

For now we could also pass an empty string which would also generate the correct route.

**Comment by robbevp** [comment]
@chvp might be an idea to use a series of boolean flags as the last param? For example: `{ indexWithScope: false, readWithoutId: false }`. Based on that we could modify the available methods
(this has the bonus that the available actions don't become more complicated, right now a module can be created with both `index` and `indexWithScope`, but this doesn't make much sense

**Comment by chvp** [comment]
An inheritance-based structure seems like a better option to me.

**Comment by robbevp** [comment]
I've created a subclass specifically for rescan, so we can better match the routes/methods from the api.

This does have the drawback that `resolveRequest` can no longer be a private method. I've renamed it to `_resolveRequest` to indicate that is not meant for external use.

(I'll rework index with scopes in a similar way, but want to keep this bugfix and that refactor separate)

**Review by chvp — APPROVED** [review]

**Pull request merged**
