### PR TITLE
Add basic test setup

### LINKED ISSUE #24: Setup basic testing
We should probably set up some basic tests to avoid regressions.

### PR DESCRIPTION
**Pull request by robbevp**
Fixes #24 

I've setup mocha to test our library so we can avoid issues like #31 

My current idea is to have a set of unit test and a set of integration test, similar to [fetch-retru](https://github.com/jonbern/fetch-retry/tree/master/test)

Tasks
- [x] Setup mocha
- [x] Setup system to detect coverage
- [x] Add some unit tests
- [x] Add some integration tests
- [x] Test generation for all routes

I don't aim for this PR to have full test coverage, but to be a good start on which we can build

## Basic overview of testing structure
* I've used mocha as the testing framework. I went with the TDD style, since we also use that in the API
* Chai is used for assertions
* nyc is used to generate coverage reports

### Tests organisation
I initially wanted to name all the test files for the file in `src` that they are testing. However, this would make the `api_module.test.ts` very big, since at some point we would want to have a basic test for each available API call.

### Mocking fetch
Mocking fetch turned out a bit of a headache, since we're running in node and not in the browser. I tried a couple of libraries/approaches to mock fetch (which we need every time we initialize an api module) and to test the fetch calls we make.

In the end, I ended up with `mock-fetch` since it allows us to test the request and sent specific responses. I would expect that we should be able to add mocked calls inside the setup or even inside a test. These mocked routes would show up in `mock-fetch`'s debug, but somehow aren't used to match the routes.

### CODE REVIEW

**Comment by robbevp** [comment]
@chvp I think you have to add codecov to this repo. The CI should correctly report it once codecov has access

**Comment by chvp** [comment]
Codecov is configured globally for the organisation to not comment.

**Comment by robbevp** [comment]
> Codecov is configured globally for the organisation to not comment.

Yeah, I noticed that is is able to add the project coverage and patch coverage as checks.

I feel like this is ready to be looked at. I wouldn't aim for this PR to provide full coverage, but just to set up the testing infrastructure.  I'll update the description with some more notes

**Review by chvp — APPROVED** [review]

**Comment by robbevp** [comment]
Main changes from yesterday:
* Rebased and added test for `PlaysScope`
* Added a basic test for every index route
* run setup of `fetch-mock` and routes before running tests and explicitly test last called url inside test

**Review by chvp — APPROVED** [review]

**Pull request merged**
